milestoneupdater/config.json
=> Add ransomware_protection app

label-updater/README.md, label-updater/composer.json, label-updater/composer.lock, label-updater/config.json, label-updater/credentials.dist.json, label-updater/run.php
=> Migrate the label handling to php

label-updater/config.json
=> Add spreed, announcementcenter and e2e

label-updater/config.json
=> Add impersonate app

tagger/tag.php
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>
=> Add stable14 branch

tagger/tag.php
=> Remove duplicate "apps" and duplicate arrays

milestoneupdater/config.json
thus i'd also run all steps: adding, closing, updating due dates
=> closing 14, opening 14.0.2 and updating due date of 14.0.1

label-updater/config.json
=> add user_retention and dont clone feedback labels

changelog/index.php
=> on error case show which repo causes issues

milestoneupdater/config.json
Basically this:
```
"dueDates": {
"Nextcloud 16.0.11": "2020-06-04",
"Nextcloud 16.0.12": "2020-07-16",
"Nextcloud 17.0.7": "2020-06-04",
"Nextcloud 17.0.8": "2020-07-16",
"Nextcloud 18.0.5": "2020-06-04",
"Nextcloud 18.0.6": "2020-07-16"
},
"closeMilestones": [
"Nextcloud 16.0.10",
"Nextcloud 17.0.6",
"Nextcloud 16.0.4"
],
"addMilestones": [
"Nextcloud 16.0.11",
"Nextcloud 16.0.12",
"Nextcloud 17.0.7",
"Nextcloud 17.0.8",
"Nextcloud 18.0.5",
"Nextcloud 18.0.6",
"Nextcloud 19"
],
```
=> Todays maintenance releases

milestoneupdater/config.json
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>
=> 19 date, add 20

changelog/index.php
@jospoortvliet I assume you use this for the changelog on the website ?
=> Add text/viewer to changelog script

milestoneupdater/composer.json, milestoneupdater/composer.lock, milestoneupdater/config.json, milestoneupdater/releases.php
* new github api package
* added package to act as cache
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>
=> Use up to date versions

setup-releases-repository/init-github-actions.sh
=> Setup the releases repository by initialising github actions

changelog/index.php
=> use native GH linking also to non-server PRs

changelog/composer.json, changelog/composer.lock, changelog/index.php
https://github.blog/changelog/2021-03-22-compare-rest-api-now-supports-pagination/
Requires an update of https://github.com/KnpLabs/php-github-api too
```sh
$ php index.php generate:changelog server v24.0.0rc1 master --verbose --format=forum
```
=> Fix commits compare pagination

changelog/index.php
Signed-off-by: John Molakvoæ <skjnldsv@protonmail.com>
=> Fix graphql error if no PR to check

tagger/tag.php
Signed-off-by: John Molakvoæ <skjnldsv@protonmail.com>
=> Don't clone the full repo to tag

tagger/tag.php
- makes it work again on the build server
@skjnldsv if i knew how to differentiate between ssh and https access without manual interaction I'd build it in…
=> switch back to SSH connection to github

label-updater/run.php
- Allow using other org repos `php run.php nextcloud-deps/myrepo`
- Github label names are case insensitive
=> Make label updater work across organizations

tagger/tag.php
=> add repo config for stable25

changelog/index.php
Signed-off-by: John Molakvoæ <skjnldsv@protonmail.com>
=> Use server `shipped.json` to get the list of repos to iterate

changelog/index.php
Avoid rate limiting and prevent this
=> Authenticate for repos get as well

collaboration-checker/check.php
=> bug(collaboration-checker): Also check nextcloud-deps org

tagger/tag.php
Follow up to #71 after running it in non-dry-run mode.
- checkout may fail, because there were no commits since te provided date to --shallow-since
- checkout may succeed, but with only newer commits as the date provided to "--until=" for git log
In both cases we now do a fresh checkout with the last 42 commits.
This successfully tagged now the two releases which were not tagged before.
=> fix two edge cases when tagging old releases

collaboration-checker/composer.lock, label-updater/composer.json, label-updater/composer.lock, label-updater/run.php, milestoneupdater/composer.json, milestoneupdater/composer.lock, milestoneupdater/releases.php
The label thing didn't execute anymore but now worked:
https://github.com/nextcloud/twofactor_nextcloud_notification/labels
```
$ php run.php --init twofactor_nextcloud_notification
PHP Fatal error:  Uncaught TypeError: ErrorException::__construct(): Argument #3 ($severity) must be of type int, Guzzle\Common\Exception\InvalidArgumentException given in /home/nickv/Nextcloud/Repositories/github_helper/label-updater/vendor/knplabs/github-api/lib/Github/HttpClient/HttpClient.php:141
Stack trace:
#0 /home/nickv/Nextcloud/Repositories/github_helper/label-updater/vendor/knplabs/github-api/lib/Github/HttpClient/HttpClient.php(141): ErrorException->__construct()
#1 /home/nickv/Nextcloud/Repositories/github_helper/label-updater/vendor/knplabs/github-api/lib/Github/HttpClient/CachedHttpClient.php(62) …
```
=> Update GitHub APIs to supported versions

changelog/index.php
include changes from the updater repo in the server release changelogs.
=> fix(changelog): include updater changes

changelog/index.php
| Before  | After |
| ------------- | ------------- |
|  ![Screenshot_20231115_222043](https://github.com/nextcloud/github_helper/assets/2184312/311d5fad-375b-4453-9784-49378524f31b) | ![Screenshot_20231115_222822](https://github.com/nextcloud/github_helper/assets/2184312/0010020f-17cc-4a67-9f4f-d35e468c8440)  |
Do you see the the dot in front of PR 40521 in *Before*? That's the backport-bot generated PRs, easy to be mistaken as done by Altahrim.
=> fix(output): sort bots' PRs to the end, and indicate them

brancher/branch.php, tagger/tag.php
- files_rightclick is discontinued
=> adjust helper tools for 28 branch-off

tagger/tag.php
fixes files_rightclick not being tagged on NC < 28 releases
=> fix(tagger): missing break

.github/workflows/dispatch-npm-engines.yml
=> fix(dispatch-npm-engines): check `package.json` existence

.github/workflows/dispatch-npm-engines.yml
=> fix(dispatch-npm-engines): force push before creating PR

brancher/branch.php, label-updater/config.json, milestoneupdater/config.json, tagger/tag.php
Adds this app to:
- brancher (for batch-generating stableXX branches)
- lable-updater (to keep a common set of labels)
- milestoneupdate (to keep common set of milestones)
- tagger (for release tagging)
(changelog generator reads automatically from shipped.json)
contributes to https://github.com/nextcloud/server/issues/44038
=> feat(apps): add files_downloadlimit

changelog/index.php
Cf. https://3v4l.org/7R28d#v8.3.4
=> fix: undefined array key warning

spdx-convertor/convert.php
used for https://github.com/nextcloud/talk-ios/pull/1723
=> Add support for spdx header conversion for swift files

spdx-convertor/convert.php
The beauty of swift and my lack of a nicely working regex (likely due to windows line-breaks)
=> Also capture @objcMembers class annotation

tagger/tag.php
=> feat(tagger): Also tag twofactor_nextcloud_notification

brancher/branch.php, milestoneupdater/config.json, tagger/tag.php
Ref: https://github.com/nextcloud-gmbh/release-script/issues/217
=> chore: add app_api to github_helper tools (branch, tag, milestone)

changelog/index.php
=> fix(Changelog): when using master as base, use an app's default branch

tagger/tag.php
=> fix: do not attempt to tag twofactor_nextcloud_notification against 29

changelog/index.php
| Before | After |
|:---------:|:------:|
|![image](https://github.com/user-attachments/assets/6faf9c6e-c1fe-47ed-95fc-d31e864e8ba8)|![image](https://github.com/user-attachments/assets/752ca1e8-fca8-4575-bfb2-dbf289778707)|
=> fix(changelog): use assigned if available on backports
